server:
  port: 10010
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    accept-count: 800

spring:
  http:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB
    enabled: true
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  messages:
    basename: message
  redis:
    database: 9
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 100
      max-idle: 10
      min-idle: 5
      max-wait: 90000
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 120000
  ConnectTimeout: 120000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:30000/eureka/
    instance:
      preferIpAddress: true
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
